services:
  node:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    container_name: socialAppDev
    ports:
      - "3000:3000"
    volumes:
      # - /app/node_modules
      - .:/app
  postgres:
    container_name: postgresSocialApp
    image: "postgres:14"
    restart: always
    environment:
      - POSTGRES_USER=hady207
      - POSTGRES_PASSWORD=2071996
    expose:
      - 5432
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data/
